
########################################################################################################################
#                                                                                                                      #
#                      Peer Seeds Configuration Options (PeerSeedsConfig)                                              #
#                                                                                                                      #
########################################################################################################################

[peer_seeds]
# DNS seeds hosts - DNS TXT records are queried from these hosts and the resulting peers added to the comms peer list.
#dns_seeds = []
# Custom specified peer seed nodes
#peer_seeds = []
# DNS name server to use for DNS seeds
#dns_seeds_name_server = "1.1.1.1:853/cloudflare-dns.com"
# All DNS seed records must pass DNSSEC validation
#dns_seeds_use_dnssec = false

[testnet.p2p.seeds]
# DNS seeds hosts - DNS TXT records are queried from these hosts and the resulting peers added to the comms peer list.
dns_seeds = []
# Custom specified peer seed nodes
peer_seeds = [
    #"a062ae2345b0db0df9fb1504b99511e23d98f8513f9b5503efcc6dad8eca7e47::/onion3/rhoqxfbzz3uidp23erxu4mkwwexc2gg4q45rcxfpbhb35ycdv4ex2fid:18141",
    #"a062ae2345b0db0df9fb1504b99511e23d98f8513f9b5503efcc6dad8eca7e47::/ip4/54.77.66.39/tcp/18189",
]
